/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Gui.Panels.*;
import Gui.Panels.Service.JpSectionClient;
import java.awt.BorderLayout;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JPanel;
/**
 *
 * @author usuario
 */
public class JfMain extends javax.swing.JFrame {
    private int xMouse;
    private int yMouse;
    private Point locationView = new Point(180, 50);
    private int[] sizeView = {844, 570};
    
    public JfMain() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        
        rePaintView(new JpPrincipal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jPanelProfile = new javax.swing.JPanel();
        jLabelProfileIcon = new javax.swing.JLabel();
        jLabelProfileLevel = new javax.swing.JLabel();
        jLabelProfileName = new javax.swing.JLabel();
        jPanelMenuActions = new javax.swing.JPanel();
        jPanelButtonMenuPrincipal = new javax.swing.JPanel();
        jLabelButtonMenuPrincipal = new javax.swing.JLabel();
        jPanelMenuPrincipalLineDecorate = new javax.swing.JPanel();
        jPanelButtonMenuService = new javax.swing.JPanel();
        jLabelButtonMenuService = new javax.swing.JLabel();
        jPanelMenuServiceLineDecorate = new javax.swing.JPanel();
        jPanelButtonMenuInventory = new javax.swing.JPanel();
        jLabelButtonMenuInventory = new javax.swing.JLabel();
        jPanelMenuInventoryLineDecorate = new javax.swing.JPanel();
        jPanelButtonMenuAdmin = new javax.swing.JPanel();
        jLabelButtonMenuAdmin = new javax.swing.JLabel();
        jPanelMenuAdminLineDecorate1 = new javax.swing.JPanel();
        jPanelNotification = new javax.swing.JPanel();
        jLabelNotificationIcon = new javax.swing.JLabel();
        jLabelNotificationEntity = new javax.swing.JLabel();
        jScrollPaneNotificationMessage = new javax.swing.JScrollPane();
        jTextAreaMessageContent = new javax.swing.JTextArea();
        jLabelNotificationError = new javax.swing.JLabel();
        jPanelNotificationClose = new javax.swing.JPanel();
        jLabelButtonMessageClose = new javax.swing.JLabel();
        jPanelView = new javax.swing.JPanel();
        jPanelNavBar = new javax.swing.JPanel();
        jPanelNavBarClose = new javax.swing.JPanel();
        jLabelButtonClose = new javax.swing.JLabel();
        jPanelNavBarBackground = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("frameMain"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(160, 173, 69));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 620));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProfile.setBackground(new java.awt.Color(160, 173, 69));
        jPanelProfile.setPreferredSize(new java.awt.Dimension(180, 80));
        jPanelProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProfileIcon.setBackground(new java.awt.Color(204, 204, 204));
        jLabelProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_profile60x40.png"))); // NOI18N
        jPanelProfile.add(jLabelProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelProfileLevel.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabelProfileLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileLevel.setText("Administrador");
        jLabelProfileLevel.setPreferredSize(new java.awt.Dimension(80, 10));
        jPanelProfile.add(jLabelProfileLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabelProfileName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelProfileName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileName.setText("Nombre apellido");
        jLabelProfileName.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelProfile.add(jLabelProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));

        jPanelMenu.add(jPanelProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenuActions.setBackground(new java.awt.Color(160, 173, 69));
        jPanelMenuActions.setEnabled(false);
        jPanelMenuActions.setFocusable(false);
        jPanelMenuActions.setPreferredSize(new java.awt.Dimension(180, 196));
        jPanelMenuActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelButtonMenuPrincipal.setBackground(new java.awt.Color(160, 173, 69));
        jPanelButtonMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonMenuPrincipal.setBackground(new java.awt.Color(140, 153, 49));
        jLabelButtonMenuPrincipal.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelButtonMenuPrincipal.setForeground(new java.awt.Color(91, 91, 91));
        jLabelButtonMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonMenuPrincipal.setText("Menu");
        jLabelButtonMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonMenuPrincipal.setFocusable(false);
        jLabelButtonMenuPrincipal.setPreferredSize(new java.awt.Dimension(180, 45));
        jLabelButtonMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuPrincipalMouseExited(evt);
            }
        });
        jPanelButtonMenuPrincipal.add(jLabelButtonMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenuPrincipalLineDecorate.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMenuPrincipalLineDecorate.setMinimumSize(new java.awt.Dimension(10, 45));
        jPanelMenuPrincipalLineDecorate.setPreferredSize(new java.awt.Dimension(10, 45));
        jPanelButtonMenuPrincipal.add(jPanelMenuPrincipalLineDecorate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanelMenuActions.add(jPanelButtonMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelButtonMenuService.setBackground(new java.awt.Color(160, 173, 69));
        jPanelButtonMenuService.setForeground(new java.awt.Color(153, 153, 153));
        jPanelButtonMenuService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonMenuService.setBackground(new java.awt.Color(140, 153, 49));
        jLabelButtonMenuService.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelButtonMenuService.setForeground(new java.awt.Color(91, 91, 91));
        jLabelButtonMenuService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonMenuService.setText("Servicio");
        jLabelButtonMenuService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonMenuService.setFocusable(false);
        jLabelButtonMenuService.setPreferredSize(new java.awt.Dimension(180, 45));
        jLabelButtonMenuService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuServiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuServiceMouseExited(evt);
            }
        });
        jPanelButtonMenuService.add(jLabelButtonMenuService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenuServiceLineDecorate.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMenuServiceLineDecorate.setMinimumSize(new java.awt.Dimension(10, 45));
        jPanelMenuServiceLineDecorate.setPreferredSize(new java.awt.Dimension(10, 45));
        jPanelButtonMenuService.add(jPanelMenuServiceLineDecorate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanelMenuActions.add(jPanelButtonMenuService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanelButtonMenuInventory.setBackground(new java.awt.Color(160, 173, 69));
        jPanelButtonMenuInventory.setForeground(new java.awt.Color(153, 153, 153));
        jPanelButtonMenuInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonMenuInventory.setBackground(new java.awt.Color(140, 153, 49));
        jLabelButtonMenuInventory.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelButtonMenuInventory.setForeground(new java.awt.Color(91, 91, 91));
        jLabelButtonMenuInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonMenuInventory.setText("Inventario");
        jLabelButtonMenuInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonMenuInventory.setFocusable(false);
        jLabelButtonMenuInventory.setPreferredSize(new java.awt.Dimension(180, 45));
        jLabelButtonMenuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuInventoryMouseExited(evt);
            }
        });
        jPanelButtonMenuInventory.add(jLabelButtonMenuInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenuInventoryLineDecorate.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMenuInventoryLineDecorate.setMinimumSize(new java.awt.Dimension(10, 45));
        jPanelMenuInventoryLineDecorate.setPreferredSize(new java.awt.Dimension(10, 45));
        jPanelButtonMenuInventory.add(jPanelMenuInventoryLineDecorate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanelMenuActions.add(jPanelButtonMenuInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanelButtonMenuAdmin.setBackground(new java.awt.Color(160, 173, 69));
        jPanelButtonMenuAdmin.setForeground(new java.awt.Color(153, 153, 153));
        jPanelButtonMenuAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonMenuAdmin.setBackground(new java.awt.Color(140, 153, 49));
        jLabelButtonMenuAdmin.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelButtonMenuAdmin.setForeground(new java.awt.Color(91, 91, 91));
        jLabelButtonMenuAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonMenuAdmin.setText("Administrador");
        jLabelButtonMenuAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonMenuAdmin.setFocusable(false);
        jLabelButtonMenuAdmin.setPreferredSize(new java.awt.Dimension(180, 45));
        jLabelButtonMenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonMenuAdminMouseExited(evt);
            }
        });
        jPanelButtonMenuAdmin.add(jLabelButtonMenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenuAdminLineDecorate1.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMenuAdminLineDecorate1.setMinimumSize(new java.awt.Dimension(10, 45));
        jPanelMenuAdminLineDecorate1.setPreferredSize(new java.awt.Dimension(10, 45));
        jPanelButtonMenuAdmin.add(jPanelMenuAdminLineDecorate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanelMenuActions.add(jPanelButtonMenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanelMenu.add(jPanelMenuActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanelNotification.setBackground(new java.awt.Color(13, 90, 177));
        jPanelNotification.setEnabled(false);
        jPanelNotification.setPreferredSize(new java.awt.Dimension(180, 130));
        jPanelNotification.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNotificationIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNotificationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_check24x24.png"))); // NOI18N
        jLabelNotificationIcon.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelNotification.add(jLabelNotificationIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelNotificationEntity.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelNotificationEntity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNotificationEntity.setText("Servicio");
        jLabelNotificationEntity.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelNotification.add(jLabelNotificationEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jScrollPaneNotificationMessage.setBackground(new java.awt.Color(13, 90, 177));
        jScrollPaneNotificationMessage.setBorder(null);
        jScrollPaneNotificationMessage.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPaneNotificationMessage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneNotificationMessage.setToolTipText("");
        jScrollPaneNotificationMessage.setOpaque(false);
        jScrollPaneNotificationMessage.setPreferredSize(new java.awt.Dimension(165, 50));
        jScrollPaneNotificationMessage.setRequestFocusEnabled(false);

        jTextAreaMessageContent.setEditable(false);
        jTextAreaMessageContent.setBackground(new java.awt.Color(13, 90, 177));
        jTextAreaMessageContent.setColumns(10);
        jTextAreaMessageContent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextAreaMessageContent.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaMessageContent.setLineWrap(true);
        jTextAreaMessageContent.setTabSize(0);
        jTextAreaMessageContent.setText("El servicio se ha guardado correctamente");
        jTextAreaMessageContent.setToolTipText("");
        jTextAreaMessageContent.setWrapStyleWord(true);
        jTextAreaMessageContent.setFocusable(false);
        jTextAreaMessageContent.setOpaque(false);
        jTextAreaMessageContent.setVerifyInputWhenFocusTarget(false);
        jScrollPaneNotificationMessage.setViewportView(jTextAreaMessageContent);

        jPanelNotification.add(jScrollPaneNotificationMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 50));

        jLabelNotificationError.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabelNotificationError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNotificationError.setText("Error : sin conexion algo asi.");
        jLabelNotificationError.setPreferredSize(new java.awt.Dimension(160, 15));
        jPanelNotification.add(jLabelNotificationError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanelNotificationClose.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNotificationClose.setOpaque(false);
        jPanelNotificationClose.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelNotificationClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonMessageClose.setBackground(new java.awt.Color(255, 42, 42));
        jLabelButtonMessageClose.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelButtonMessageClose.setForeground(new java.awt.Color(204, 204, 204));
        jLabelButtonMessageClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonMessageClose.setText("X");
        jLabelButtonMessageClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonMessageClose.setFocusable(false);
        jLabelButtonMessageClose.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabelButtonMessageClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMessageCloseMouseClicked(evt);
            }
        });
        jPanelNotificationClose.add(jLabelButtonMessageClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelNotification.add(jPanelNotificationClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanelMenu.add(jPanelNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelView.setPreferredSize(new java.awt.Dimension(844, 570));

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelView, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jPanelNavBar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNavBar.setOpaque(false);
        jPanelNavBar.setPreferredSize(new java.awt.Dimension(1024, 50));
        jPanelNavBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelNavBarMouseDragged(evt);
            }
        });
        jPanelNavBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelNavBarMousePressed(evt);
            }
        });
        jPanelNavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavBarClose.setBackground(new java.awt.Color(204, 204, 204));
        jPanelNavBarClose.setOpaque(false);
        jPanelNavBarClose.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanelNavBarClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonClose.setBackground(new java.awt.Color(255, 42, 42));
        jLabelButtonClose.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabelButtonClose.setForeground(new java.awt.Color(102, 102, 102));
        jLabelButtonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonClose.setText("X");
        jLabelButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonClose.setFocusable(false);
        jLabelButtonClose.setPreferredSize(new java.awt.Dimension(35, 35));
        jLabelButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonCloseMouseExited(evt);
            }
        });
        jPanelNavBarClose.add(jLabelButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanelNavBar.add(jPanelNavBarClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 5, 40, 40));

        jPanelNavBarBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNavBarBackground.setPreferredSize(new java.awt.Dimension(844, 50));
        jPanelNavBar.add(jPanelNavBarBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        getContentPane().add(jPanelNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuPrincipalMouseEntered
        Style.BtnMenu.Entered(jPanelButtonMenuPrincipal, jLabelButtonMenuPrincipal);
    }//GEN-LAST:event_jLabelButtonMenuPrincipalMouseEntered

    private void jLabelButtonMenuPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuPrincipalMouseExited
        Style.BtnMenu.Exited(jPanelButtonMenuPrincipal, jLabelButtonMenuPrincipal);
    }//GEN-LAST:event_jLabelButtonMenuPrincipalMouseExited

    private void jLabelButtonMenuServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuServiceMouseEntered
        Style.BtnMenu.Entered(jPanelButtonMenuService, jLabelButtonMenuService);
    }//GEN-LAST:event_jLabelButtonMenuServiceMouseEntered

    private void jLabelButtonMenuServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuServiceMouseExited
        Style.BtnMenu.Exited(jPanelButtonMenuService, jLabelButtonMenuService);
    }//GEN-LAST:event_jLabelButtonMenuServiceMouseExited

    private void jLabelButtonCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCloseMouseEntered
        Style.BtnClose.entered(jLabelButtonClose);
    }//GEN-LAST:event_jLabelButtonCloseMouseEntered

    private void jLabelButtonCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCloseMouseExited
        Style.BtnClose.exited(jLabelButtonClose);
    }//GEN-LAST:event_jLabelButtonCloseMouseExited

    private void jLabelButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelButtonCloseMouseClicked

    private void jLabelButtonMenuInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuInventoryMouseEntered
        Style.BtnMenu.Entered(jPanelButtonMenuInventory, jLabelButtonMenuInventory);
    }//GEN-LAST:event_jLabelButtonMenuInventoryMouseEntered

    private void jLabelButtonMenuInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuInventoryMouseExited
        Style.BtnMenu.Exited(jPanelButtonMenuInventory, jLabelButtonMenuInventory);
    }//GEN-LAST:event_jLabelButtonMenuInventoryMouseExited

    private void jLabelButtonMenuAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuAdminMouseEntered
        Style.BtnMenu.Entered(jPanelButtonMenuAdmin, jLabelButtonMenuAdmin);
    }//GEN-LAST:event_jLabelButtonMenuAdminMouseEntered

    private void jLabelButtonMenuAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuAdminMouseExited
        Style.BtnMenu.Exited(jPanelButtonMenuAdmin, jLabelButtonMenuAdmin);
    }//GEN-LAST:event_jLabelButtonMenuAdminMouseExited

    private void jLabelButtonMessageCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMessageCloseMouseClicked
        jPanelNotification.setVisible(false);
    }//GEN-LAST:event_jLabelButtonMessageCloseMouseClicked

    private void jPanelNavBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNavBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelNavBarMousePressed

    private void jPanelNavBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNavBarMouseDragged
        int xCurrent = evt.getXOnScreen();
        int yCurrent = evt.getYOnScreen();
        this.setLocation(xCurrent - xMouse, yCurrent - yMouse);
    }//GEN-LAST:event_jPanelNavBarMouseDragged

    private void jLabelButtonMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuPrincipalMouseClicked
        rePaintView(new JpPrincipal());
        btnSelected(jLabelButtonMenuPrincipal.getText());
    }//GEN-LAST:event_jLabelButtonMenuPrincipalMouseClicked

    private void jLabelButtonMenuServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuServiceMouseClicked
        rePaintView(new JpSectionClient());
        btnSelected(jLabelButtonMenuService.getText());
    }//GEN-LAST:event_jLabelButtonMenuServiceMouseClicked

    private void jLabelButtonMenuInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuInventoryMouseClicked
        rePaintView(new JpInventory());
        btnSelected(jLabelButtonMenuInventory.getText());
    }//GEN-LAST:event_jLabelButtonMenuInventoryMouseClicked

    private void jLabelButtonMenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMenuAdminMouseClicked
        rePaintView(new JpLogs());
        btnSelected(jLabelButtonMenuAdmin.getText());
    }//GEN-LAST:event_jLabelButtonMenuAdminMouseClicked
    
    private void btnSelected (String component) {
        Style.BtnMenu.disable(jPanelButtonMenuPrincipal, jLabelButtonMenuPrincipal, jPanelMenuPrincipalLineDecorate);
        Style.BtnMenu.disable(jPanelButtonMenuService, jLabelButtonMenuService, jPanelMenuServiceLineDecorate);
        Style.BtnMenu.disable(jPanelButtonMenuInventory, jLabelButtonMenuInventory, jPanelMenuInventoryLineDecorate);
        Style.BtnMenu.disable(jPanelButtonMenuAdmin, jLabelButtonMenuAdmin, jPanelMenuAdminLineDecorate1);
        
        switch (component.toLowerCase()){
            case "menu":
                Style.BtnMenu.active(jPanelButtonMenuPrincipal, jLabelButtonMenuPrincipal, jPanelMenuPrincipalLineDecorate);
                break;
            case "servicio":
                Style.BtnMenu.active(jPanelButtonMenuService, jLabelButtonMenuService, jPanelMenuServiceLineDecorate);
                break;
            case "inventario":
                Style.BtnMenu.active(jPanelButtonMenuInventory, jLabelButtonMenuInventory, jPanelMenuInventoryLineDecorate);
                break;
            case "administrador":
                Style.BtnMenu.active(jPanelButtonMenuAdmin, jLabelButtonMenuAdmin, jPanelMenuAdminLineDecorate1);
                break;
            default:
                break;
        }
        
    }
    
    private void rePaintView(JPanel content) {
        content.setSize(844, 570);
        content.setLocation(0, 0);
        jPanelView.removeAll();
        jPanelView.add(content, BorderLayout.CENTER);
        jPanelView.revalidate();
        jPanelView.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelButtonClose;
    private javax.swing.JLabel jLabelButtonMenuAdmin;
    private javax.swing.JLabel jLabelButtonMenuInventory;
    private javax.swing.JLabel jLabelButtonMenuPrincipal;
    private javax.swing.JLabel jLabelButtonMenuService;
    private javax.swing.JLabel jLabelButtonMessageClose;
    public static javax.swing.JLabel jLabelNotificationEntity;
    public static javax.swing.JLabel jLabelNotificationError;
    private javax.swing.JLabel jLabelNotificationIcon;
    private javax.swing.JLabel jLabelProfileIcon;
    private javax.swing.JLabel jLabelProfileLevel;
    private javax.swing.JLabel jLabelProfileName;
    private javax.swing.JPanel jPanelButtonMenuAdmin;
    private javax.swing.JPanel jPanelButtonMenuInventory;
    private javax.swing.JPanel jPanelButtonMenuPrincipal;
    private javax.swing.JPanel jPanelButtonMenuService;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMenuActions;
    private javax.swing.JPanel jPanelMenuAdminLineDecorate1;
    private javax.swing.JPanel jPanelMenuInventoryLineDecorate;
    private javax.swing.JPanel jPanelMenuPrincipalLineDecorate;
    private javax.swing.JPanel jPanelMenuServiceLineDecorate;
    private javax.swing.JPanel jPanelNavBar;
    private javax.swing.JPanel jPanelNavBarBackground;
    private javax.swing.JPanel jPanelNavBarClose;
    public static javax.swing.JPanel jPanelNotification;
    private javax.swing.JPanel jPanelNotificationClose;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JPanel jPanelView;
    public static javax.swing.JScrollPane jScrollPaneNotificationMessage;
    public static javax.swing.JTextArea jTextAreaMessageContent;
    // End of variables declaration//GEN-END:variables
}
