/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.tabs.JPanelInventory;
import view.tabs.JPanelPrincipal;
import view.tabs.JPanelLogs;
import view.behavior.Style;
import view.tabs.JPanelServiceClient;
import java.awt.BorderLayout;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import view.behavior.IButtonSelected;
import view.behavior.IWindowActions;
import view.components.ButtonMenu;
/**
 *
 * @author usuario
 */
public class JFrameMain extends javax.swing.JFrame implements IWindowActions{
    public JFrameMain() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        jPanelNotification.setVisible(false);
        jPanelProfile.setVisible(false);
        rePaintView(new JPanelPrincipal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNavBar = new javax.swing.JPanel();
        jPanelNavBarClose = new javax.swing.JPanel();
        jLabelButtonClose = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jPanelProfile = new javax.swing.JPanel();
        jLabelProfileIcon = new javax.swing.JLabel();
        jLabelProfileLevel = new javax.swing.JLabel();
        jLabelProfileName = new javax.swing.JLabel();
        jPanelMenuActions = new javax.swing.JPanel();
        buttonMenuPrincipal = new view.components.ButtonMenu();
        buttonMenuService = new view.components.ButtonMenu();
        buttonMenuInventory = new view.components.ButtonMenu();
        buttonMenuLogs = new view.components.ButtonMenu();
        buttonMenuAdmin = new view.components.ButtonMenu();
        jPanelNotification = new javax.swing.JPanel();
        jLabelNotificationIcon = new javax.swing.JLabel();
        jLabelNotificationEntity = new javax.swing.JLabel();
        jScrollPaneNotificationMessage = new javax.swing.JScrollPane();
        jTextAreaMessageContent = new javax.swing.JTextArea();
        jLabelNotificationError = new javax.swing.JLabel();
        jPanelNotificationClose = new javax.swing.JPanel();
        jLabelButtonMessageClose = new javax.swing.JLabel();
        jPanelView = new javax.swing.JPanel();
        jPanelBackground = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frameMain"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavBar.setBackground(new java.awt.Color(0, 0, 0));
        jPanelNavBar.setOpaque(false);
        jPanelNavBar.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanelNavBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelNavBarMouseDragged(evt);
            }
        });
        jPanelNavBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelNavBarMousePressed(evt);
            }
        });
        jPanelNavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavBarClose.setBackground(new java.awt.Color(204, 204, 204));
        jPanelNavBarClose.setOpaque(false);
        jPanelNavBarClose.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanelNavBarClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelNavBar.add(jPanelNavBarClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 5, 40, 40));

        jLabelButtonClose.setBackground(new java.awt.Color(255, 42, 42));
        jLabelButtonClose.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabelButtonClose.setForeground(new java.awt.Color(102, 102, 102));
        jLabelButtonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonClose.setText("X");
        jLabelButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelButtonClose.setFocusable(false);
        jLabelButtonClose.setPreferredSize(new java.awt.Dimension(35, 35));
        jLabelButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonCloseMouseExited(evt);
            }
        });
        jPanelNavBar.add(jLabelButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 40));

        getContentPane().add(jPanelNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenu.setBackground(new java.awt.Color(13, 90, 177));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(150, 500));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProfile.setBackground(new java.awt.Color(160, 173, 69));
        jPanelProfile.setEnabled(false);
        jPanelProfile.setOpaque(false);
        jPanelProfile.setPreferredSize(new java.awt.Dimension(180, 80));
        jPanelProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProfileIcon.setBackground(new java.awt.Color(204, 204, 204));
        jLabelProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfileIcon.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanelProfile.add(jLabelProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jLabelProfileLevel.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabelProfileLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileLevel.setText("Administrador");
        jLabelProfileLevel.setPreferredSize(new java.awt.Dimension(80, 10));
        jPanelProfile.add(jLabelProfileLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, -1, -1));

        jLabelProfileName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelProfileName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileName.setText("Nombre apellido");
        jLabelProfileName.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelProfile.add(jLabelProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 10, 100, -1));

        jPanelMenu.add(jPanelProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jPanelMenuActions.setBackground(new java.awt.Color(160, 173, 69));
        jPanelMenuActions.setEnabled(false);
        jPanelMenuActions.setFocusable(false);
        jPanelMenuActions.setOpaque(false);
        jPanelMenuActions.setPreferredSize(new java.awt.Dimension(150, 245));
        jPanelMenuActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonMenuPrincipal.setForeground(new java.awt.Color(204, 204, 204));
        buttonMenuPrincipal.setText("Menu");
        buttonMenuPrincipal.setPreferredSize(new java.awt.Dimension(150, 45));
        buttonMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuPrincipalMouseClicked(evt);
            }
        });
        jPanelMenuActions.add(buttonMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonMenuService.setForeground(new java.awt.Color(204, 204, 204));
        buttonMenuService.setText("Servicio");
        buttonMenuService.setPreferredSize(new java.awt.Dimension(150, 45));
        buttonMenuService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuServiceMouseClicked(evt);
            }
        });
        jPanelMenuActions.add(buttonMenuService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        buttonMenuInventory.setForeground(new java.awt.Color(204, 204, 204));
        buttonMenuInventory.setText("Inventario");
        buttonMenuInventory.setPreferredSize(new java.awt.Dimension(150, 45));
        buttonMenuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuInventoryMouseClicked(evt);
            }
        });
        jPanelMenuActions.add(buttonMenuInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        buttonMenuLogs.setForeground(new java.awt.Color(204, 204, 204));
        buttonMenuLogs.setText("Informes");
        buttonMenuLogs.setPreferredSize(new java.awt.Dimension(150, 45));
        buttonMenuLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuLogsMouseClicked(evt);
            }
        });
        jPanelMenuActions.add(buttonMenuLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        buttonMenuAdmin.setForeground(new java.awt.Color(204, 204, 204));
        buttonMenuAdmin.setText("Administrador");
        buttonMenuAdmin.setPreferredSize(new java.awt.Dimension(150, 45));
        buttonMenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuAdminMouseClicked(evt);
            }
        });
        jPanelMenuActions.add(buttonMenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jPanelMenu.add(jPanelMenuActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanelNotification.setBackground(new java.awt.Color(13, 90, 177));
        jPanelNotification.setEnabled(false);
        jPanelNotification.setPreferredSize(new java.awt.Dimension(150, 120));
        jPanelNotification.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNotificationIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNotificationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icon_check24x24.png"))); // NOI18N
        jLabelNotificationIcon.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelNotification.add(jLabelNotificationIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelNotificationEntity.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelNotificationEntity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNotificationEntity.setText("Servicio");
        jLabelNotificationEntity.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelNotification.add(jLabelNotificationEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jScrollPaneNotificationMessage.setBackground(new java.awt.Color(13, 90, 177));
        jScrollPaneNotificationMessage.setBorder(null);
        jScrollPaneNotificationMessage.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPaneNotificationMessage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneNotificationMessage.setToolTipText("");
        jScrollPaneNotificationMessage.setOpaque(false);
        jScrollPaneNotificationMessage.setPreferredSize(new java.awt.Dimension(165, 50));
        jScrollPaneNotificationMessage.setRequestFocusEnabled(false);

        jTextAreaMessageContent.setEditable(false);
        jTextAreaMessageContent.setBackground(new java.awt.Color(13, 90, 177));
        jTextAreaMessageContent.setColumns(10);
        jTextAreaMessageContent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextAreaMessageContent.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaMessageContent.setLineWrap(true);
        jTextAreaMessageContent.setTabSize(0);
        jTextAreaMessageContent.setText("El servicio se ha guardado correctamente");
        jTextAreaMessageContent.setToolTipText("");
        jTextAreaMessageContent.setWrapStyleWord(true);
        jTextAreaMessageContent.setFocusable(false);
        jTextAreaMessageContent.setOpaque(false);
        jTextAreaMessageContent.setPreferredSize(new java.awt.Dimension(150, 60));
        jTextAreaMessageContent.setVerifyInputWhenFocusTarget(false);
        jScrollPaneNotificationMessage.setViewportView(jTextAreaMessageContent);

        jPanelNotification.add(jScrollPaneNotificationMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 50));

        jLabelNotificationError.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabelNotificationError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNotificationError.setText("Error : sin conexion algo asi.");
        jLabelNotificationError.setPreferredSize(new java.awt.Dimension(160, 15));
        jPanelNotification.add(jLabelNotificationError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanelNotificationClose.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNotificationClose.setOpaque(false);
        jPanelNotificationClose.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelNotificationClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButtonMessageClose.setBackground(new java.awt.Color(255, 42, 42));
        jLabelButtonMessageClose.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelButtonMessageClose.setForeground(new java.awt.Color(204, 204, 204));
        jLabelButtonMessageClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonMessageClose.setText("X");
        jLabelButtonMessageClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelButtonMessageClose.setFocusable(false);
        jLabelButtonMessageClose.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabelButtonMessageClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMessageCloseMouseClicked(evt);
            }
        });
        jPanelNotificationClose.add(jLabelButtonMessageClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelNotification.add(jPanelNotificationClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanelMenu.add(jPanelNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelView.setPreferredSize(new java.awt.Dimension(650, 450));

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelView, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int xMouse;
    private int yMouse;
    private List<ButtonMenu> btnSelected = initButtonsMenu();
    
    private ArrayList<ButtonMenu> initButtonsMenu(){
        ArrayList<ButtonMenu> temp = new ArrayList<>();
        temp.add(buttonMenuPrincipal);
        temp.add(buttonMenuService);
        temp.add(buttonMenuInventory);
        temp.add(buttonMenuLogs);
        temp.add(buttonMenuAdmin);
        
        return temp;
    }
    
    private void jLabelButtonCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCloseMouseEntered
        Style.Button.feel(Style.Colors.buttonCloseEntered, jLabelButtonClose);
    }//GEN-LAST:event_jLabelButtonCloseMouseEntered

    private void jLabelButtonCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCloseMouseExited
        Style.Button.feel(Style.Colors.buttonCloseEntered, jLabelButtonClose);
    }//GEN-LAST:event_jLabelButtonCloseMouseExited

    private void jLabelButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCloseMouseClicked
        close();
    }//GEN-LAST:event_jLabelButtonCloseMouseClicked

    private void jLabelButtonMessageCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMessageCloseMouseClicked
        jPanelNotification.setVisible(false);
    }//GEN-LAST:event_jLabelButtonMessageCloseMouseClicked

    private void jPanelNavBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNavBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelNavBarMousePressed

    private void jPanelNavBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNavBarMouseDragged
        int xCurrent = evt.getXOnScreen();
        int yCurrent = evt.getYOnScreen();
        this.setLocation(xCurrent - xMouse, yCurrent - yMouse);
    }//GEN-LAST:event_jPanelNavBarMouseDragged

    private void buttonMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuPrincipalMouseClicked
        buttonDeselected();
        buttonMenuPrincipal.selected();
        rePaintView(new JPanelPrincipal());
    }//GEN-LAST:event_buttonMenuPrincipalMouseClicked

    private void buttonMenuServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuServiceMouseClicked
        buttonDeselected();
        buttonMenuService.selected();
        rePaintView(new JPanelServiceClient());
    }//GEN-LAST:event_buttonMenuServiceMouseClicked

    private void buttonMenuInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuInventoryMouseClicked
        buttonDeselected();
        buttonMenuInventory.selected();
        rePaintView(new JPanelInventory());
    }//GEN-LAST:event_buttonMenuInventoryMouseClicked

    private void buttonMenuLogsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuLogsMouseClicked
        buttonDeselected();
        buttonMenuLogs.selected();
        rePaintView(new JPanelLogs());
    }//GEN-LAST:event_buttonMenuLogsMouseClicked

    private void buttonMenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuAdminMouseClicked
        buttonDeselected();
        buttonMenuAdmin.selected();
        //rePaintView(null);
    }//GEN-LAST:event_buttonMenuAdminMouseClicked

    private void buttonDeselected() {
        btnSelected.stream().forEach(item -> item.setSelected(false));
    }
    
    private void rePaintView(JPanel content) {
        content.setSize(844, 570);
        content.setLocation(0, 0);
        jPanelView.removeAll();
        jPanelView.add(content, BorderLayout.CENTER);
        jPanelView.revalidate();
        jPanelView.repaint();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.components.ButtonMenu buttonMenuAdmin;
    private view.components.ButtonMenu buttonMenuInventory;
    private view.components.ButtonMenu buttonMenuLogs;
    private view.components.ButtonMenu buttonMenuPrincipal;
    private view.components.ButtonMenu buttonMenuService;
    private javax.swing.JLabel jLabelButtonClose;
    private javax.swing.JLabel jLabelButtonMessageClose;
    public static javax.swing.JLabel jLabelNotificationEntity;
    public static javax.swing.JLabel jLabelNotificationError;
    private javax.swing.JLabel jLabelNotificationIcon;
    private javax.swing.JLabel jLabelProfileIcon;
    private javax.swing.JLabel jLabelProfileLevel;
    private javax.swing.JLabel jLabelProfileName;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMenuActions;
    private javax.swing.JPanel jPanelNavBar;
    private javax.swing.JPanel jPanelNavBarClose;
    public static javax.swing.JPanel jPanelNotification;
    private javax.swing.JPanel jPanelNotificationClose;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JPanel jPanelView;
    public static javax.swing.JScrollPane jScrollPaneNotificationMessage;
    public static javax.swing.JTextArea jTextAreaMessageContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public void navBarDrag(int xMouse, int yMouse) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void close() {
        System.exit(0);
    }
}
