/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.behavior.IWindowActions;

/**
 *
 * @author usuario
 */
public class JFrameLogin extends javax.swing.JFrame implements IWindowActions{

    /**
     * Creates new form JfLogin
     */
    public JFrameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelNavBar = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jLabelLoginTitle = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPass = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("frameLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaneContent.setBackground(new java.awt.Color(255, 255, 255));
        jPaneContent.setPreferredSize(new java.awt.Dimension(400, 500));
        jPaneContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavBar.setOpaque(false);
        jPanelNavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClose.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButtonClose.setText("X");
        jButtonClose.setToolTipText("");
        jPanelNavBar.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jPanel1.add(jPanelNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jPaneContent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelLoginTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelLoginTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLoginTitle.setText("Tubings del caribe");
        jPaneContent.add(jLabelLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jButtonLogin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonLogin.setText("Ingresar");
        jPaneContent.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 130, 40));
        jPaneContent.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 40));
        jPaneContent.add(jTextFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 40));

        jLabelUser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser.setText("Usuario");
        jPaneContent.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabelPass.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPass.setText("Contraseña");
        jPaneContent.add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        getContentPane().add(jPaneContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelLoginTitle;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPaneContent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNavBar;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void navBarDrag(int xMouse, int yMouse) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
